language: python
python:
- '2.7'
install:
- pip install -U platformio
script:
- pio --version
- pio run -e generic -e relayboard -e debug
before_deploy:
- cd ..
- tar -zcf ${TRAVIS_BUILD_DIR}-${TRAVIS_TAG}.tar.gz -C ${TRAVIS_BUILD_DIR}/bin .
deploy:
  provider: releases
  file: "${TRAVIS_BUILD_DIR}-${TRAVIS_TAG}.tar.gz"
  skip_cleanup: true
  on:
    repo: Pako2/esp-rfid
    all_branches: true
